# Docker image from https://hub.docker.com
image: "ubuntu:bionic"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch

cache:
  paths:
    - libcaide/dist/
    - libcaide/cbits/build/

before_script:
  - uname -a
  - apt-get update -yqq
  - DEBIAN_FRONTEND=noninteractive apt-get install -yqq --no-install-recommends g++ gcc make cmake binutils python zlib1g-dev ghc cabal-install mono-mcs phantomjs curl wget netbase

Build and test:
  script:
    - ci/gitlab.sh
  artifacts:
    paths:
      - libcaide/dist/build/caide/caide

