# Docker image from https://hub.docker.com
image: "ubuntu:bionic"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - uname -a
  - apt-get update -yqq
  - DEBIAN_FRONTEND=noninteractive apt-get install -yqq --no-install-recommends build-essential g++ gcc binutils cmake mono-mcs phantomjs cabal-install ghc git

build_and_test:
  script:
    - ci/gitlab.sh

