# Docker image from https://hub.docker.com
image: "ubuntu:bionic"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - uname -a
  - apt-get update -yqq
  - DEBIAN_FRONTEND=noninteractive apt-get install -yqq --no-install-recommends git build-essential g++ gcc binutils cmake python zlib1g-dev ghc cabal-install mono-mcs phantomjs

Build and test:
  script:
    - ci/gitlab.sh

