version: 2.1

jobs:
  build:
    parameters:
      publish_artifacts:
        type: string
        default: ""

    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout

      - run: git submodule status | md5sum | awk '{print $1}' > cppinliner-submodule-id.txt
      - restore_cache:
          key: v2-ccache-{{ checksum "cppinliner-submodule-id.txt" }}

      - restore_cache:
          key: v1-caide-cabal-sandbox-{{ checksum "libcaide/cabal.config" }}

      - run: .circleci/build-and-test.sh

      - when:
          condition: <<parameters.publish_artifacts>>
          steps:
            - store_artifacts:
                path: libcaide/dist/build/caide/caide

      - save_cache:
          key: v2-ccache-{{ checksum "cppinliner-submodule-id.txt" }}
          paths:
            - ~/.ccache

      - save_cache:
          key: v1-caide-cabal-sandbox-{{ checksum "libcaide/cabal.config" }}
          paths:
            - libcaide/.cabal-sandbox/



workflows:
  version: 2
  on_commit:
    jobs:
      - build

  nightly:
    jobs:
      - build:
          publish_artifacts: "true"
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: [ circleci ]

